### ISSUE TITLE
Première barrière rouge se réinitialise 

### ISSUE THREAD

**Issue by Noopss** [imikado/dupotBeatAndMatchToPass#1]
Après avoir combattu quelques ennemis, la barre de remplissage pour ouvrir la barrière était presque remplie. J'ai tué 2 ennemis à peu de temps d'intervalle. Le premier a lâché un bonus qui a permis d'ouvrir la barrière. Le bonus du deuxième ennemi a lui aussi été remplir la jauge de la barrière, ce qui a eu pour effet de la remettre à zéro et de refermer la barrière.

Testé sur Google Chrome Version 104.0.5112.80 (Build officiel) (64 bits)

**Comment by imikado** [comment]
Lut,
C'est en effet pas clair dans la démo actuel, mais c'est une particularité du jeu: on doit "juste" tuer le nombre d'enemie necessaire pour debloquer les barrières, pas plus sinon ça rebloque, ça oblige a éviter certains enemis , rendant le gameplay un peu plus dur que juste frapper tout ce qui bouge ;)
